//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int idCompetition { get; set; }
        public string titleCompetition { get; set; }
        public System.DateTime startDateCompetition { get; set; }
        public System.DateTime endDateCompetition { get; set; }
        public string cityCompetition { get; set; }
        public int regionCode { get; set; }
        public Nullable<int> skillId { get; set; }
        public string descriptionCompetition { get; set; }
        public string photoPathCompetition { get; set; }
        public string logoPathCompetition { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
