//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.Competition = new HashSet<Competition>();
            this.User = new HashSet<User>();
        }
    
        public int idSkill { get; set; }
        public string nameSkill { get; set; }
        public bool isFutureSkill { get; set; }
        public int skillBlockId { get; set; }
        public int NumberCompetitorSkill { get; set; }
        public int NumberExpertSkill { get; set; }
        public double WorkPlaceArea { get; set; }
        public double StoreArea { get; set; }
        public double MarkRoomArea { get; set; }
        public double BriffingRoomArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition> Competition { get; set; }
        public virtual SkillBlock SkillBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
