//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string FirstNameUser { get; set; }
        public string LastNameUser { get; set; }
        public string PatronymicUser { get; set; }
        public string PINUser { get; set; }
        public string PasswordUser { get; set; }
        public Nullable<int> roleId { get; set; }
        public string phoneNumberUser { get; set; }
        public string emailUser { get; set; }
        public Nullable<int> skillId { get; set; }
        public int regionCode { get; set; }
        public Nullable<int> competitionUser { get; set; }
        public Nullable<int> placeUser { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Role Role { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
